#!/usr/bin/env bash

#
# server
#
# Script for creating a server,
# depending on the cwd and the installed packages.
#
# Author: André König <andre.koenig@posteo.de>, Tyll Weiß <inkdpixels@gmail.com>
#

#
# Installation script
#

SHELLTYPE="$(basename /$SHELL)"

if [ $SHELLTYPE = "bash" ]; then
    if [ -f "$HOME/.bashrc" ]; then
        DETECTED_PROFILE="$HOME/.bashrc"
    elif [ -f "$HOME/.bash_profile" ]; then
        DETECTED_PROFILE="$HOME/.bash_profile"
    fi
    elif [ $SHELLTYPE = "zsh" ]; then
        DETECTED_PROFILE="$HOME/.zshrc"
fi

if [ -z $DETECTED_PROFILE ]; then
    if [ -f "$PROFILE" ]; then
        DETECTED_PROFILE="$PROFILE"
    elif [ -f "$HOME/.profile" ]; then
        DETECTED_PROFILE="$HOME/.profile"
    elif [ -f "$HOME/.bashrc" ]; then
        DETECTED_PROFILE="$HOME/.bashrc"
    elif [ -f "$HOME/.bash_profile" ]; then
        DETECTED_PROFILE="$HOME/.bash_profile"
    elif [ -f "$HOME/.zshrc" ]; then
        DETECTED_PROFILE="$HOME/.zshrc"
    fi
fi

echo "export PATH=$PATH:`pwd`" >> $DETECTED_PROFILE && source $DETECTED_PROFILE
