#!/usr/bin/env bash

#
# server
#
# Script for creating a server,
# depending on the cwd and the installed packages.
#
# Usage: server --type <type> --port <port>
#
# Author: Tyll Weiß <inkdpixels@gmail.com>
#

# Retrieve all arguments.

#
# Read command line arguments.
#
while [[ $# > 1 ]]
do
  key="$1"

  case $key in
    --port)
    PORT="$2"
    shift
    ;;

    --type)
    TYPE="$2"
    shift
    ;;
  esac
  shift
done

#
# Set fallbacks for command line arguments.
#
if [[ -z $PORT ]]; then
  PORT="8000"
fi

#
# Test whether a command exists.
#
command_exists() {
  if [ `type -P $1` ]; then
    return 0
  fi
  return 1
}

#
# Log helper.
#
p_fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"

  exit 1;
}

#
# shortcut for ./flow server:run
#
run_flow_server() {
  ./flow server:run --port $PORT

  exit 0;
}

#
# shortcut for the interal php server.
#
run_php_server() {
  php -S localhost:$PORT

  exit 0;
}

#
# shortcut for the http-server node package.
#
run_node_server() {
  http-server -p $PORT

  exit 0;
}

#
# If a certain type parameter was passed to the script, try to run it.
#
if [ -n "$TYPE" ]; then
  case "$TYPE" in
    flow)
      run_flow_server ;;
    php)
      run_php_server ;;
    node)
      run_node_server ;;
    *)
  esac

  exit 0;
fi

#
# If no type parameter was passed,
# cover the internal flow command if the file is found in the cwd.
#
if [ -f flow ]; then
  run_flow_server

#
# Next up, try to run the internal PHP server (Only for PHP version =< 5.4.0)
# ToDo: Check the current php version.
#
elif command_exists "php"; then
  run_php_server

#
# Finally, node's http-server package.
#
elif command_exists "http-server"; then
  run_node_server

#
# Nope!
#
else
  p_fail "No server availabe, please install PHP v 5.4.0 or higher OR run `npm i -g http-server`."
fi
